### ISSUE TITLE
you broked it shiney

### ISSUE THREAD

**Issue by IAmTomahawkx** [ShineyDev/pretty#1]
it no work sir. 
```python
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/prettify_exceptions/__init__.py", line 26, in excepthook
    print("".join(formatter.format_exception(*args)).strip())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/prettify_exceptions/formatter.py", line 167, in format_exception
    yield from self.format_traceback(exc_traceback, limit=limit)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/prettify_exceptions/formatter.py", line 250, in format_traceback
    capture_locals=capture_locals, lookup_lines=lookup_lines))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/prettify_exceptions/formatter.py", line 210, in format_list
    frame, filename, lineno, name, line)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/prettify_exceptions/formatter.py", line 289, in format_list_frame
    line = self.colorize_tree(tree, line)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/prettify_exceptions/formatter.py", line 328, in colorize_tree
    source = line[node.col_offset:node.end_col_offset]
AttributeError: 'Expr' object has no attribute 'end_col_offset'

Original exception was:
Traceback (most recent call last):
  File "/Volumes/BD-PC/bot/xlydn/launcher.py", line 20, in <module>
    3+"e"
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by ShineyDev** [comment]
https://github.com/ShineyDev/prettify.py/commit/e45349cfd9862f3d12aff1b6e42b506635f20cb2
